#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# Release Parameters
BASE_VERSION=0.1.7
IS_RELEASE=false

SOURCE_REPO=agent-sdk
RELEASE_REPO=trustbloc/${SOURCE_REPO}
SNAPSHOT_REPO=trustbloc-cicd/snapshot
NPM_AGENT_PKG_BASE_NAME=agent-sdk-web
NPM_SDK_PKG_BASE_NAME=wallet-sdk
DOCKER_PKG_NAME=agent-sdk-server

DOCKER_RELEASE_REPO=ghcr.io/trustbloc
DOCKER_SNAPSHOT_REPO=ghcr.io/trustbloc-cicd

NPM_RELEASE_PREFIX=trustbloc
NPM_SNAPSHOT_PREFIX=trustbloc-cicd

if [ ${IS_RELEASE} = false ]
then
  EXTRA_VERSION=snapshot-$(git rev-parse --short=7 HEAD)
  PROJECT_VERSION=${BASE_VERSION}-${EXTRA_VERSION}
  PROJECT_PKG_REPO=${SNAPSHOT_REPO}
  NPM_PKG_NAME_PREFIX=${NPM_SNAPSHOT_PREFIX}
  DOCKER_PROJECT_PKG_REPO=${DOCKER_SNAPSHOT_REPO}
else
  PROJECT_VERSION=${BASE_VERSION}
  PROJECT_PKG_REPO=${RELEASE_REPO}
  NPM_PKG_NAME_PREFIX=${NPM_RELEASE_PREFIX}
  DOCKER_PROJECT_PKG_REPO=${DOCKER_RELEASE_REPO}
fi

export NPM_PKG_TAG=${PROJECT_VERSION}
export NPM_AGENT_PKG_NAME=${NPM_PKG_NAME_PREFIX}/${NPM_AGENT_PKG_BASE_NAME}
export NPM_SDK_PKG_NAME=${NPM_PKG_NAME_PREFIX}/${NPM_SDK_PKG_BASE_NAME}
export NPM_PKG_REPO=${PROJECT_PKG_REPO}
export AGENT_SDK_TAG=${PROJECT_VERSION}
export AGENT_SDK_PKG=${DOCKER_PROJECT_PKG_REPO}/${DOCKER_PKG_NAME}
